name: Dispatch
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v2
      with:
        application_id: ${{ secrets.APP_ID }}
        application_private_key: ${{ secrets.APP_PEM }}
    - uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Hello World
        token: ${{ steps.get_workflow_token.outputs.token }}
        ref: main
